create table public.ozon_product_report_wide (
  id bigserial not null,
  store_id text not null,
  day date not null,
  product_id text not null,
  product_title text null,
  category_l1 text null,
  category_l2 text null,
  category_l3 text null,
  brand text null,
  model text null,
  sales_scheme text null,
  sku text null,
  article text null,
  abc_by_amount text null,
  abc_by_qty text null,
  amount_ordered numeric(18, 2) null,
  amount_ordered_delta numeric(18, 4) null,
  amount_share numeric(10, 6) null,
  amount_share_delta numeric(10, 6) null,
  search_position_avg numeric(10, 4) null,
  search_position_delta numeric(10, 4) null,
  impressions_total bigint null,
  impressions_total_delta numeric(18, 4) null,
  conv_impr_to_order numeric(10, 6) null,
  conv_impr_to_order_delta numeric(10, 6) null,
  impressions_search_catalog bigint null,
  impressions_search_catalog_delta numeric(18, 4) null,
  conv_sc_to_cart numeric(10, 6) null,
  conv_sc_to_cart_delta numeric(10, 6) null,
  add_to_cart_from_sc bigint null,
  add_to_cart_from_sc_delta numeric(18, 4) null,
  conv_sc_to_card numeric(10, 6) null,
  conv_sc_to_card_delta numeric(10, 6) null,
  product_card_visits bigint null,
  product_card_visits_delta numeric(18, 4) null,
  conv_card_to_cart numeric(10, 6) null,
  conv_card_to_cart_delta numeric(10, 6) null,
  add_to_cart_from_card bigint null,
  add_to_cart_from_card_delta numeric(18, 4) null,
  conv_overall_to_cart numeric(10, 6) null,
  conv_overall_to_cart_delta numeric(10, 6) null,
  add_to_cart_total bigint null,
  add_to_cart_total_delta numeric(18, 4) null,
  conv_cart_to_order numeric(10, 6) null,
  conv_cart_to_order_delta numeric(10, 6) null,
  items_ordered bigint null,
  items_ordered_delta numeric(18, 4) null,
  items_delivered bigint null,
  items_delivered_delta numeric(18, 4) null,
  conv_order_to_buyout numeric(10, 6) null,
  conv_order_to_buyout_delta numeric(10, 6) null,
  items_buyout bigint null,
  items_buyout_delta numeric(18, 4) null,
  items_cancel_by_cancel_date bigint null,
  items_cancel_by_cancel_date_delta numeric(18, 4) null,
  items_cancel_by_order_date bigint null,
  items_cancel_by_order_date_delta numeric(18, 4) null,
  items_return_by_return_date bigint null,
  items_return_by_return_date_delta numeric(18, 4) null,
  items_return_by_order_date bigint null,
  items_return_by_order_date_delta numeric(18, 4) null,
  avg_price numeric(14, 2) null,
  avg_price_delta numeric(14, 4) null,
  discount_from_your_price numeric(10, 6) null,
  discount_from_your_price_delta numeric(10, 6) null,
  price_index numeric(10, 6) null,
  promo_days integer null,
  ad_spend_ratio numeric(10, 6) null,
  ad_spend_ratio_delta numeric(10, 6) null,
  promoted_days integer null,
  oos_days_28d integer null,
  ending_stock bigint null,
  fbo_supply_advice text null,
  fbo_supply_qty integer null,
  avg_delivery_days numeric(10, 4) null,
  reviews_count integer null,
  product_rating numeric(10, 4) null,
  inserted_at timestamp with time zone not null default now(),
  constraint ozon_product_report_wide_pkey primary key (id),
  constraint ozon_prw_uniq unique (store_id, day, product_id)
) TABLESPACE pg_default;

create index IF not exists idx_ozon_prw_store_day on public.ozon_product_report_wide using btree (store_id, day) TABLESPACE pg_default;

create index IF not exists idx_ozon_prw_store_prod on public.ozon_product_report_wide using btree (store_id, product_id) TABLESPACE pg_default;